language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
branches:
  only:
    - master
    
+test:
+ override:
+ - mkdir -p $CIRCLE_TEST_REPORTS/cucumber
+ - bundle exec cucumber --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber

